version: '3'
services:
  tradesystem-zookeeper:
    restart: always
    image: confluentinc/cp-zookeeper:5.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 52181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - 52181:52181
  tradesystem-kafka:
    restart: always
    image: confluentinc/cp-kafka:5.3.0
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:59092
      KAFKA_ZOOKEEPER_CONNECT: tradesystem-zookeeper:52181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 59092:59092

