version: '3'
services:
  tradesystem-zookeeper:
    restart: always
    image: wurstmeister/zookeeper
  tradesystem-kafka:
    restart: always
    image: wurstmeister/kafka:2.12-2.2.1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: tradesystem-zookeeper:2181
    ports:
      - 9092:9092

