version: '3'
volumes:
  tradesystem-mysql-data:
    driver: local
services:
  tradesystem-mysql:
    restart: always
    image: mysql:8.0.16
    volumes:
      - tradesystem-mysql-data:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=tradesystem
    ports:
      - 53306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
